Repository Azure/secrets-store-csi-driver-provider-azure, pull requests merged in 2020-10, with the labels that each got.

#288 chore: helm dep update for lint + lint manifest_staging
  .gitignore
  Makefile
Labels: test

#285 Allow the 'updateStrategy' of the Daemonset to be configured in Helm
  manifest_staging/charts/csi-secrets-store-provider-azure/README.md
  manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml
  manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml
  manifest_staging/charts/csi-secrets-store-provider-azure/values.yaml
Labels: helm

#276 feat: switch to using HostToContainer instead of Bidirectional
  manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer-windows.yaml
  manifest_staging/charts/csi-secrets-store-provider-azure/templates/provider-azure-installer.yaml
  manifest_staging/deployment/provider-azure-installer-windows.yaml
  manifest_staging/deployment/provider-azure-installer.yaml
Labels: enhancement

#277 feat: add golangci lint and enable in CI
  .gitignore
  .golangci.yml
  Makefile
  azure-pipelines.yml
  pkg/provider/provider.go
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: enhancement
